#!/bin/bash

if [ $2 ]; then
    project_name=$2
elif find ../.project_name.txt | grep ".project_name.txt" > /dev/null; then
    project_name=$(cat ../.project_name.txt)
else
    read -p "Project name : " project_name
fi

echo "/*" > $1.c
echo "** EPITECH PROJECT, 2025" >> $1.c
echo "** $project_name" >> $1.c
echo "** File description:" >> $1.c
echo "** $1.c" >> $1.c
echo "*/" >> $1.c
echo >> $1.c

echo '#include "my.h"' >> $1.c
echo >> $1.c

echo "int $1(void)" >> $1.c
echo "{" >> $1.c
if [ "$1" == "main" ]; then
    echo "    ${project_name%.*}();" >> $1.c
fi
echo "    return 0;" >> $1.c
echo "}" >> $1.c
