#!/bin/bash

if [ $1 ]; then
    lib_name=$1
else
    read -p "Lib name : " lib_name
fi

if [[ $lib_name == *".a" ]]; then
    mkdir -p ${lib_name%.*}
    cd ${lib_name%.*}

    echo $lib_name > .project_name.txt

    mkdir -p src
    cd src
    Cnew ${lib_name%.*} $lib_name
    cd ..

    Makenew $lib_name

    mkdir -p include
    cd include
    Hnew ${lib_name%.*} $project_name
    cd ..

    .clang
    gitignore ${project_name%.*}

    add_libs
fi
