#!/bin/bash

if [ $1 ]; then
    project_name=$1
elif find .. -name .project_name.txt | grep ".project_name.txt" > /dev/null; then
    project_name=$(cat .project_name.txt)
else
    read -p "Project name : " project_name
fi

echo "##" > Makefile
echo "## EPITECH PROJECT, 2024" >> Makefile
echo "## $project_name" >> Makefile
echo "## File description:" >> Makefile
echo "## Makefile" >> Makefile
echo "##" >> Makefile
echo >> Makefile

echo   "NAME    :=  ${project_name%.*}" >> Makefile

if [[ $project_name == *".c" ]]; then
    cat /home/l/my_scripts/OtherFiles/Makefile1 >> Makefile
elif [[ $project_name == *".a" ]]; then
    cat /home/l/my_scripts/OtherFiles/Makefile2 >> Makefile
fi
